<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-AQIQLLBC" failures="0" tests="4" name="SeleniumConcept.day4" time="1.026" errors="1" timestamp="3 Feb 2025 05:13:29 GMT" skipped="0">
  <testcase classname="SeleniumConcept.day4" name="mobileSignInCar" time="0.002"/>
  <testcase classname="SeleniumConcept.day4" name="mobileSignoutCar" time="0.001"/>
  <testcase classname="SeleniumConcept.day4" name="apiBikeLoan" time="1.020">
    <error message="Method SeleniumConcept.day4.apiBikeLoan() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method SeleniumConcept.day4.apiBikeLoan() didn't finish within the time-out 1000
	at java.base@18.0.1.1/java.lang.InterruptedException.<init>(InterruptedException.java:67)
	at java.base@18.0.1.1/java.lang.Thread.sleep(Native Method)
	at app//SeleniumConcept.day4.apiBikeLoan(day4.java:28)
	at java.base@18.0.1.1/java.lang.invoke.LambdaForm$DMH/0x0000000800d6d800.invokeVirtual(LambdaForm$DMH)
	at java.base@18.0.1.1/java.lang.invoke.LambdaForm$MH/0x0000000800d70400.invoke(LambdaForm$MH)
	at java.base@18.0.1.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base@18.0.1.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
	at java.base@18.0.1.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base@18.0.1.1/java.lang.reflect.Method.invoke(Method.java:577)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base@18.0.1.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@18.0.1.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@18.0.1.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@18.0.1.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@18.0.1.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- apiBikeLoan -->
  <testcase classname="SeleniumConcept.day4" name="apiCarLoan" time="0.003"/>
</testsuite> <!-- SeleniumConcept.day4 -->
